production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_key:      <%= ENV['SECRET_KEY'] %>
  secret_token:    <%= ENV['SECRET_TOKEN'] %>
  papper:          <%= ENV['PAPPER'] %>
  mailer_sender:   <%= ENV['MAIL_SENDER'] %>
  default_url_options: <%= ENV['DEFAULT_URL_OPTIONS'] %>
  smtp:
    address:              smtp.mandrillapp.com
    authentication:       plain
    port:                 587
    user_name:            <%= ENV['SMTP_USER_NAME'] %>
    password:             <%= ENV['SMTP_PASSWORD'] %>
