production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_key:      <%= ENV['SECRET_KEY'] %>
  secret_token:    <%= ENV['SECRET_TOKEN'] %>
  papper:          <%= ENV['PAPPER'] %>
  mailer_sender:   <%= ENV['MAIL_SENDER'] %>
